kind: pipeline
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
#   - npm test
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec ./node_modules/.bin/codecov
  - ./node_modules/.bin/codecov
