kind: pipeline
type: docker
name: codecov

steps:
- name: codecov
  image: node:8
  commands:
  - npm install
  - npm install -g istanbul
  - istanbul cover ./node_modules/mocha/bin/_mocha || ./node_modules/.bin/codecov

# trigger:
#   branch:
#   - master

---
kind: pipeline
type: docker
name: test

steps:
- name: test
  image: node:8
  commands:
  - npm install
  - npm test

# trigger:
#   branch:
#   - master
